#!/bin/sh

# This script gets NetworkManager out of suspend.
case $1 in
     suspend|suspend_hybrid|hibernate)
        # No need to do anything here.
         ;;
     resume|thaw)
         nmcli nm sleep false
         ;;
 esac
