"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "J. Fernando Sánchez"
email = "j@sanchezrada.es"

[[--scope]]
--when.repositories = ["~/git/work/tcs"]
[--scope.user]
name = "J. Fernando Sánchez"
email = "f.sanchez@thechannelstore.tv"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
l = ["log"]
s = ["status"]
f = ["git", "fetch"]
p = ["git", "push"]

[ui]
pager = "delta"
diff-formatter = "delta"
paginate = "auto"
default-command = ["log", "--reversed"]
merge-editor = "meld"

[merge-tools.delta]
diff-args = ["--side-by-side", "$left", "$right", "--width=$width"]

[revset-aliases]
'private_commits()' = "description('[local]')"
