#!/bin/zsh
python2 $HOME/.bin/i3-wm-scripts/nextmatch.py tmux
if [ $? -gt 0 ]; then
    urxvt -e tmux attach & sleep 0.1 && python2 $HOME/.bin/i3-wm-scripts/nextmatch.py tmux
fi
if [ "$#" -gt 0 ]; then
    eval "tmux neww"
    sleep 0.2
    xdotool type "$*"
    xdotool key Return
fi
