#!/bin/sh
case $1 in
    "single")
    #xrandr --auto --output eDP1 --primary --output DP1 --off
        ~/.screenlayout/gsi-single.sh
        xrandr --output HDMI1 --off --output DVI-1 --off --output DP1 --off --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output VGA1 --off
    ;;
    "dual")
        case $2 in
            "home")
                xrandr --output DP1 --off --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 0x1080 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VGA1 --off
                ;;
            *)
            #xrandr --auto --output eDP1 --primary --right-of DP1
            xrandr --output VIRTUAL1 --off --output DP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output eDP1 --mode 1920x1080 --pos 1920x0 --rotate normal --output VGA1 --off
            xrandr --output "DVI-1-0" --off
            ;;
        esac
    ;;
esac
if [ `command -v nitrogen` ]; then
    nitrogen --restore
fi
