#!/bin/sh
if [ "$#" -lt 1 ]; then
   ls -1 ~/.screenlayout | rofi -dmenu | xargs -I '{}' sh "$HOME/.screenlayout/{}"  || exit
else
   sh $HOME/.screenlayout/$1.sh
fi
if [ `command -v nitrogen` ]; then
    nitrogen --restore
fi
