#!/bin/sh

if command -v myrofi >/dev/null 2>&1;
then
    launcher="myrofi -dmenu -no-show-icons -i -mesg '""$input""'"
else
    launcher="dmenu -fn  "-*-cure-medium-*-*-*-11-*-*-*-*-*-*-*" -nb "#101010" -nf "#5f5f5f" -sb "#191
fi

 # find "$input" -maxdepth 1 ! -path "$input" -print | sh -c "$launcher" | xargs $0
conname=$(nmcli -t -f NAME con | sh -c "$launcher")
nmcli conn up "$conname" || nmcli conn down $conname
